site_name: Python RQL Library
site_url: https://github.com/cloudblue/lib-rql
repo_name: cloudblue/lib-rql
repo_url: https://github.com/cloudblue/lib-rql
edit_uri: ""
copyright: Copyright &copy; 2023 Ingram Micro. All Rights Reserved.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cloudblue
    - icon: material/home
      link: https://connect.cloudblue.com/community/
extra_css:
  - css/custom.css
theme:
  name: "material"
  logo: images/logo_full.png
  favicon: images/favicon.ico
  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "blue"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - toc:
      toc_depth: 3
plugins:
  - glightbox
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true
            merge_init_into_class: true
            show_source: false
  - autorefs
watch:
  - docs
  - py_rql
nav:
  - Home: index.md
  - Guide: guide.md
  - API Reference: reference.md
